### ISSUE TITLE
[Unit Testing] Don't exit the app on device, so that you can actually take advantage of the View Test Results functionality

### ISSUE THREAD

**Issue by enchev** [NativeScript/nativescript-unit-test-runner#10]
_From @ikoevska on October 30, 2015 13:41_

Right now, whether my unit tests fail or succeed, the deployed testable app exits right after the test execution. This prevents me from tapping the View Test Results Details button and review the details in the test log. 

Although, usually the console shows the details from the test runs, there are cases (like when the app disconnects or the test fails with not particular info in the log) when I'd like to view the details in the app. So far, I have been able to make use of this button one time.

_Copied from original issue: NativeScript/nativescript-cli#1125_

**Comment by enchev** [comment]
_From @NathanaelA on November 6, 2015 21:49_

Uhm, can we leave this a configurable item.  I happen to prefer it to exit right away.  That allows me to programmatically know the tests are done.

**Comment by enchev** [comment]
_From @dtopuzov on November 11, 2015 8:51_

Agree, this should be a configurable item.

**Comment by enchev** [comment]
_From @tailsu on December 8, 2015 8:55_

I think that the "View Test Results" functionality should be removed entirely. It's a leftover from the time when tests could work without connection to a Karma server.

**Comment by dtopuzov** [comment]
It looks most people (including me) prefer exiting the app (current behavior).
