### ISSUE TITLE
tns test <platform> include coverage?

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/nativescript-unit-test-runner#12]
_From @NickIliev on June 20, 2016 10:56_

_From @georgeedwards on June 17, 2016 12:46_
## Feature Request:

Can the `tns test <platform>` command include coverage reporting as part of it's output? [Karma-Coverage](https://github.com/karma-runner/karma-coverage) seems to be quite a nice way of doing this. To add support for Typescript, adding in [remap-istanbul](https://github.com/SitePen/remap-istanbul) looks to be the most straight forward solution. 

_Copied from original issue: NativeScript/NativeScript#2333_

_Copied from original issue: NativeScript/nativescript-cli#1865_

**Comment by casche** [comment]
@NickIliev @georgeedwards is anyone working on this or is there an eta ⌛️ ? 

I've tried to get this executing with istanbul:

```javascript

    files: [
      'app/**/*.js',
    ],

    preprocessors: {
      'app/**/!(*spec).js': ['coverage']
    },

    reporters: ['progress', 'coverage'],
```

But it just generates an empty report. I can't really tell what ```tns test``` is really doing to debug it. Or am I just missing something simple ? 😞

**Comment by joeskeen** [comment]
@casche I was really struggling with this as well, but I just got it working.  Could you post your full `karma.conf.js` file and I can compare it with what I have?

**Comment by casche** [comment]
@joeskeen thanks! 👍 I added those lines you suggested and now I get the same report as you. That is, files are listed but coverage is not increasing.

**Comment by phattranky** [comment]
My Karma config:

`
module.exports = function(config) {
  config.set({

    // base path that will be used to resolve all patterns (eg. files, exclude)
    basePath: '',


    // frameworks to use
    // available frameworks: https://npmjs.org/browse/keyword/karma-adapter
    frameworks: ['jasmine'],

    // plugins: ['karma-jasmine', 'karma-nativescript-launcher', 'karma-typescript-preprocessor', 'karma-typescript', 'karma-coverage', 'karma-remap-coverage'],


    // list of files / patterns to load in the browser
    files: [
      'node_modules/nativescript-angular/zone-js/dist/zone-nativescript.js',
      'node_modules/zone.js/dist/long-stack-trace-zone.js',
      'node_modules/zone.js/dist/proxy.js',
      'node_modules/zone.js/dist/sync-test.js',
      'node_modules/zone.js/dist/jasmine-patch.js',
      'node_modules/zone.js/dist/async-test.js',
      'node_modules/zone.js/dist/fake-async-test.js',
      'app/**/*.ts'
    ],


    // list of files to exclude
    exclude: [
    ],


    // preprocess matching files before serving them to the browser
    // available preprocessors: https://npmjs.org/browse/keyword/karma-preprocessor
    preprocessors: {
       'app/**/*.ts': ['typescript'],
       'app/**/!(*spec).ts': ['typescript', 'coverage']
    },

    typescriptPreprocessor: {
      // options passed to the typescript compiler 
      options: {
        project: './tsconfig.json'
      },
      // transforming the filenames 
      transformPath: function(path) {
        return path.replace(/\.ts$/, '.js');
      }
    },

    // test results reporter to use
    // possible values: 'dots', 'progress'
    // available reporters: https://npmjs.org/browse/keyword/karma-reporter
    reporters: ['progress', 'coverage', 'remap-coverage'],


    // web server port
    port: 9876,


    // enable / disable colors in the output (reporters and logs)
    colors: true,


    // level of logging
    // possible values: config.LOG_DISABLE || config.LOG_ERROR || config.LOG_WARN || config.LOG_INFO || config.LOG_DEBUG
    logLevel: config.LOG_INFO,


    // enable / disable watching file and executing tests whenever any file changes
    autoWatch: true,


    // start these browsers
    // available browser launchers: https://npmjs.org/browse/keyword/karma-launcher
    browsers: [],

    customLaunchers: {
      android: {
        base: 'NS',
        platform: 'android'
      },
      ios: {
        base: 'NS',
        platform: 'ios'
      },
      ios_simulator: {
        base: 'NS',
        platform: 'ios',
        arguments: ['--emulator']
      }
    },

    /*
    coverageReporter: {
      // specify a common output directory
      dir: './coverage',
      reporters: [
          { type: 'lcov', subdir: '.' }
      ],
      includeAllSources: true
    },*/
    coverageReporter: {
      type: 'in-memory'
    },

    remapCoverageReporter: {
      'text-summary': null,
      html: './coverage/html',
      cobertura: './coverage/cobertura.xml'
    },

    // Continuous Integration mode
    // if true, Karma captures browsers, runs the tests and exits
    singleRun: true
  })
}

`
Got same issue, the coverage reporter always empty. If add the coverageReporter.includeAllSources, it listing all file, but the report values not changes, and always 0 like @casche

**Comment by dtopuzov** [comment]
This issue was moved to NativeScript/nativescript-cli#2772
