### ISSUE TITLE
How to uninstall unit test completely?

### ISSUE THREAD

**Issue by ryc16** [NativeScript/nativescript-unit-test-runner#14]
I have two questions. #1. How to get it running. #2. How to uninstall unit test. 

Follow the instruction to install unit test and I picked jasmine. Unfortunately, I couldn't get it running. I got "no reachable hosts". My emulator is running different ip or subnet from dev machine.  ie. My emulator is running 10.71.34.101 and my dev machine is 192.168.0.101. I try using different addresses below on the chrome browser. 

http://10.71.34.1:9877
http://192.168.0.101:9877
http://127.0.0.1:9877

But all give the same result "no reachable hosts".

Also I got below from console but no idea what is wrong.

Chrome 51.0.2704 (Windows 10 0.0.0) ERROR
  Uncaught ReferenceError: require is not defined
  at app/app.js:1

I have to give up for now but now I try to uninstall unit test but couldn't find a simple way. ie. tns plugin nativescript-unit-test-runner. Now when I run >tns livesync android. I am getting unwanted message. I try to delete the karma.conf.js but I couldn't even run my app at all. I got 

21 07 2016 11:30:44.684:ERROR [config]: File <project>\karma.conf.js does not exist!
Test run failed.

Please advice a simple way to perform clean uninstallation. For now, I just manually npm uninstall every package but not sure it is clean and correct way.

```
>tns info
All NativeScript components versions information
┌──────────────────┬─────────────────┬────────────────┬───────────────┐
│ Component        │ Current version │ Latest version │ Information   │
│ nativescript     │ 2.1.1           │ 2.1.1          │ Up to date    │
│ tns-core-modules │ 2.1.0           │ 2.1.0          │ Up to date    │
│ tns-android      │ 2.1.1           │ 2.1.1          │ Up to date    │
│ tns-ios          │                 │ 2.1.1          │ Not installed │
└──────────────────┴─────────────────┴────────────────┴───────────────┘
```

**Comment by dtopuzov** [comment]
Can't help much with the networking. 
In general what you need is emulator and PC to see each other.

Re uninstall: 
```
tns plugin remove nativescript-unit-test-runner
{delete all other dev dependecies in package.json}
rm -rf karma.conf.js
rm -rf hooks
```
In your case you still have unit testing hooks in hook folder and they try to find karma.conf.js
