### ISSUE TITLE
Add ability to test UI widgets

### ISSUE THREAD

**Issue by PeterStaev** [NativeScript/nativescript-unit-test-runner#9]
From what I see currently it is not possible to test UI widgets. I tried to parse a widget with `builder.parse` or just create a new object inside the test and set up properties/bindings but both approaches do not initialize the widget fully (i.e. on android the `_createUI` function is not called, on iOS `onLoaded` event is never fired). Would be great if we can add tests for UI widgets (especially for people developing UI plugins :))

**Comment by dtopuzov** [comment]
This issue was moved to NativeScript/nativescript-cli#2774
